[default.extend-words]
"élégance" = "élégance"
"ressources" = "ressources"
"certains" = "certains"
"adresse" = "adresse"
"informations" = "informations"
"Entreprise" = "Entreprise"
"cours" = "cours"
"sur" = "sur"
"ESPACE" = "ESPACE"
"manuels" = "manuels"
"projet" = "projet"
"PRINCIPALES" = "PRINCIPALES"
"Informations" = "Informations"
"Langage" = "Langage"
"Ratatui" = "Ratatui"
"Criticals" = "Criticals"
